
title: Legal documents | Hackers@UPC
description: > # this means to ignore newlines until "baseurl:"
  Collection of all legal documents from HackersAtUPC and HackUPC. 
  Some documents are: Legal Notice, Privacy and Cookies Policy, Terms and Conditions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://legal.hackersatupc.org/" # the base hostname & protocol for your site
twitter_username: hackersatupc
github_username:  hackupc

collections:
  documents:
    output: true
    layout: document
    permalink: /:categories/:title

permalink: /:title
